// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;   
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfhaJwf3AfWmf7qcgTMoDz1X4jr_-VVYg',
    appId: '1:1078137266468:web:70eee7c833372dae6453b1',
    messagingSenderId: '1078137266468',
    projectId: 'pande-batanguena-c9525',
    authDomain: 'pande-batanguena-c9525.firebaseapp.com',
    storageBucket: 'pande-batanguena-c9525.firebasestorage.app',
    measurementId: 'G-H229XLEVCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtRtRDkEGww_YguDFT84WR4f3-aVscojc',
    appId: '1:1078137266468:android:3ebbbb76037d53656453b1',
    messagingSenderId: '1078137266468',
    projectId: 'pande-batanguena-c9525',
    storageBucket: 'pande-batanguena-c9525.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyOwXNvpuw7CuGtnhlJ5KETtcCMiWxhoQ',
    appId: '1:1078137266468:ios:544ac540bab103e36453b1',
    messagingSenderId: '1078137266468',
    projectId: 'pande-batanguena-c9525',
    storageBucket: 'pande-batanguena-c9525.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyOwXNvpuw7CuGtnhlJ5KETtcCMiWxhoQ',
    appId: '1:1078137266468:ios:544ac540bab103e36453b1',
    messagingSenderId: '1078137266468',
    projectId: 'pande-batanguena-c9525',
    storageBucket: 'pande-batanguena-c9525.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfhaJwf3AfWmf7qcgTMoDz1X4jr_-VVYg',
    appId: '1:1078137266468:web:146950b0a63b619d6453b1',
    messagingSenderId: '1078137266468',
    projectId: 'pande-batanguena-c9525',
    authDomain: 'pande-batanguena-c9525.firebaseapp.com',
    storageBucket: 'pande-batanguena-c9525.firebasestorage.app',
    measurementId: 'G-KK2GC2LL0C',
  );
}
